// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Implementations of various xsync commands

pub mod cargo_lock;
pub mod cargo_toml;
pub mod rust_toolchain_toml;

pub use self::cargo_lock::CargoLock;
pub use self::cargo_toml::CargoToml;
pub use self::rust_toolchain_toml::RustToolchainToml;

const GENERATED_HEADER: &str = r#"
# Copyright (C) Microsoft Corporation. All rights reserved.

################################################################################
#                                                                              #
#                    !! DO NOT MANUALLY UPDATE THIS FILE !!                    #
#                                                                              #
################################################################################
#                                                                              #
# This file is automatically @generated by OpenVMM's `xsync` tooling.          #
#                                                                              #
# Please refer to the instructions in `Cargo.xsync.toml` for what steps are    #
# required to regenerate this file.                                            #
#                                                                              #
################################################################################

"#;
